# Generated by Django 4.1.5 on 2023-02-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_rename_writer_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
