# Generated by Django 4.1.5 on 2023-02-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bool_like_users',
            field=models.BooleanField(default=False),
        ),
    ]
