# Generated by Django 4.1.5 on 2023-02-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_alter_post_bool_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subsription',
            name='sub_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
