# Generated by Django 4.1.5 on 2023-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0007_alter_sentence_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='translate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
