# Generated by Django 4.1.5 on 2023-02-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0008_sentence_is_valid_sentence_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsription',
            name='sub_nickname',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
