# Generated by Django 4.1.5 on 2023-02-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0009_subsription_sub_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='day_of_the_week',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
