# Generated by Django 4.1.5 on 2023-03-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0014_post_unknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
