# Generated by Django 4.1.5 on 2023-03-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0016_remove_sentence_is_valid_remove_sentence_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='korean',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
