# Generated by Django 4.1.5 on 2023-01-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
