# Generated by Django 4.1.5 on 2023-02-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
