# Generated by Django 4.1.5 on 2023-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_num',
            field=models.IntegerField(null=True),
        ),
    ]
