# Generated by Django 4.1.5 on 2023-02-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_liked_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_num',
        ),
    ]
