# Generated by Django 4.1.5 on 2023-02-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_liked_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
